# Generated by Django 3.1.3 on 2020-11-08 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201108_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='facebook',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AddField(
            model_name='main',
            name='instagram',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AddField(
            model_name='main',
            name='skype',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AddField(
            model_name='main',
            name='twitter',
            field=models.CharField(default='-', max_length=200),
        ),
    ]
