# Generated by Django 3.1.3 on 2020-11-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='name',
        ),
        migrations.AddField(
            model_name='blog',
            name='title',
            field=models.CharField(default='-', max_length=200),
        ),
    ]
