# Generated by Django 3.1.3 on 2020-11-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201109_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='long_text',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='blog',
            name='quote_text',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='blog',
            name='short_text',
            field=models.TextField(default='-'),
        ),
    ]
